### ISSUE TITLE
Fingerprints and int.64

### ISSUE THREAD

**Issue by MichaelaBrezinova** [mqcomplab/bitbirch#11]
Hi, thank you for the great tool! :) It is quite easy to use and very fast.

I just have a few small questions:

- I saw in the paper you said that the tool should work for any fingerprints, should I expect it to be just matter of person’s choice as for classic Taylor Butina? I saw that in your code, you are using the count fingerprints, is there a specific reason for it? My intention was to use tool with classic bit Morgan FP with length 1024. Do you think this should work fine with this tool?

- I saw in other issues users encountering branching factor error and you recommended to use int.64. Why is this necessary even when handling simple data as binary arrays? I saw the same error when using count fingerprints (did not get this error for bit fingerprints) 

- Also, I saw in the previous issues you mentioned that it is doable to run the bitbirch on a laptop while using int.64, however, my MacBook pro with m3 chip had issues clustering around 3.5miĺion int64 fingerprints. Did you make any code optimizations to enable this to run smoothly?

Thank you very much,
Best wishes,
Michaela

**Comment by MichaelaBrezinova** [comment]
Also just for reference - the clusterings I did were with (similarity) threshold 0.78, as I want to get clusters with relatively highly similar molecules. Thank you!

**Comment by ramirandaq** [comment]
Hi Michaela, thanks for trying BitBIRCH. Regarding your questions:
1- Yes, the method will work for any binary fingerprints, just like traditional Taylor-Butina. All the equations and code are general in the sense that they only assume that the user is passing an array of 1s and 0s, no other assumptions are made about the input.
2- A key part of BitBIRCH (one that reduces memory usage in the long run) is that the elements of a cluster are stored as their sum. That is, if you have a cluster with two molecules: mol1 = [0 1 0 1 0] and mol2 = [0 1 0 1 1], what is actually stored is:
linear_sum = [0 2 0 2 1]. So, we need to be able to add mol1 and mol2, which will be problematic if the dtype is bit. The easiest solution to this is to use int64, but other dtypes (i.e., int32), could work as well, depending on the total number of molecules you might want to cluster. int64 is just, by far, the safest choice.
On the type of fingerprints: BitBIRCH, as presently constructed, only works for binary arrays. Using a different type of input will cause errors. In the code we use for the preprint (https://www.biorxiv.org/content/10.1101/2024.08.10.607459v1) only binary fingerprints were used, and no errors were found. If you are interested in using count fingerprints send me an email to see how we could help.
3- I've done up to a million (I just ran a test now with 1M 2048 bits fingerprints) in my laptop with the code that's in GitHub.
4- That's indeed a quite strict similarity threshold, but in our tests we went all the way to 0.8 (in some cases, even 0.85), and everything ran smoothly.
5- Final comment on efficiency: if you cannot run the 3.5M at once you can either: A) pass chunks of data to the same BitBirch object sequentially, or B) run the parallel/iterative version that we mentioned in the paper.
Let us know if you run into any issues, we are happy to help. Keep us posted with the issues about fp type.

**Comment by MichaelaBrezinova** [comment]
Hi, thank you so much for your response! 

Ah I see, in the notebook in dataset splitting I saw GetCountFingerprintAsNumPy being used so I thought you are doing count fingerprints because I havent used this command before ( I only used GetMorganFingerprintAsBitVect method before). 

I will try again with int.64 (or int.32) and hopefully it works okay. 

If I had too many molecules and wanted to do it sequentially as you suggested, do you mean doing bitbirch.fit call sequentially for batches of the data? Would this impact clustering results or it should not?

Thank you so much again,
Best,
Michaela

**Comment by MichaelaBrezinova** [comment]
Ah great, Thank you for your reply. Regarding doing bitbirch sequentially as you suggested in case of too many mols, does this mean doing bitbirch.fit call sequentially for batches of the data? Would this impact clustering results or it should not?

Thank you again,
Best wishes,
Michaela

**Comment by ramirandaq** [comment]
@MichaelaBrezinova doing BitBIRCH sequentially on batches of data is not going to change your results. Let's say your 2D array of fingerprints is F. Then if you do:

A) brc = BitBIRCH()
    brc.fit(F)

OR

B) brc = BitBIRCH()
    brc.fit(F[:500000])
    brc.fit(F[500000:])

you'll get exactly the same results in the end.

As @khuddzu mentioned, the best way to proceed with the fingerprints is to convert the SMILES to bit fingerprints, and then be sure to turn those to int32 or int64.

**Comment by MichaelaBrezinova** [comment]
Ah I see, Thank you very much, I will try that then!

Best,
Michaela
