### ISSUE TITLE
Small cluster sizes with ECFP4 fps + RDKit fp exception

### ISSUE THREAD

**Issue by greg-rezo** [mqcomplab/bitbirch#8]
Hi,
Thanks for providing this method and code. I'm excited to try it out on clustering large libraries. 

I tried running it on the [CHEMBL 233 Ki](https://github.com/molML/MoleculeACE/blob/main/MoleculeACE/Data/benchmark_data/old/CHEMBL233_Ki.csv) set and ran into two issues:

1) For ECFP4 fingerprints, I can't get fewer than 1165 clusters out of the 3142 compounds, even going down to the (unrealistic) similarity threshold of 0.01:
```
BitBirch: sim_thresh=0.01, top_sizes: 11, 11, 10, 10, 10, count: 1165
BitBirch: sim_thresh=0.35, top_sizes: 9, 8, 8, 8, 8, count: 1387
BitBirch: sim_thresh=0.5, top_sizes: 8, 8, 7, 7, 7, count: 1497
BitBirch: sim_thresh=0.7, top_sizes: 7, 7, 7, 7, 6, count: 1673
BitBirch: sim_thresh=0.9, top_sizes: 5, 5, 5, 4, 4, count: 2465
BitBirch: sim_thresh=0.99, top_sizes: 4, 4, 4, 4, 3, count: 3066
```
(counts are from the cluster ids returned by `BitBirch.get_cluster_mol_ids()`)

For reference, RDKit's `rdkit.ML.Cluster.Butina.ClusterData` returns <200 clusters at similarity threshold 0.35:
```
RDKit: sim_thresh=0.35, top_sizes: 467, 212, 195, 164, 157, count: 186
RDKit: sim_thresh=0.5, top_sizes: 165, 160, 158, 109, 103, count: 375
RDKit: sim_thresh=0.7, top_sizes: 58, 57, 54, 44, 41, count: 1059
RDKit: sim_thresh=0.9, top_sizes: 13, 9, 7, 6, 6, count: 2844
RDKit: sim_thresh=0.99, top_sizes: 3, 3, 3, 3, 3, count: 3099
```

2) For RDKit fingerprints (`rdFingerprintGenerator.GetRDKitFPGenerator` which are used in the paper AFAICT), I hit an exception:
```
common/biochem/cluster.py:558: in __call__
    bb.fit(fp_array)
../.venv/lib/python3.10/site-packages/bitbirch/bitbirch.py:482: in fit
    return self._fit(X)
../.venv/lib/python3.10/site-packages/bitbirch/bitbirch.py:523: in _fit
    split = self.root_.insert_bf_subcluster(subcluster, set_bits)
../.venv/lib/python3.10/site-packages/bitbirch/bitbirch.py:285: in insert_bf_subcluster
    split_child = closest_subcluster.child_.insert_bf_subcluster(subcluster, set_bits)
../.venv/lib/python3.10/site-packages/bitbirch/bitbirch.py:329: in insert_bf_subcluster
    self.append_subcluster(subcluster)
../.venv/lib/python3.10/site-packages/bitbirch/bitbirch.py:252: in append_subcluster
    self.init_centroids_[n_samples] = subcluster.centroid_
E   IndexError: index 51 is out of bounds for axis 0 with size 51
```
(with default `branching_factor`=50)

Appreciate your help.

**Comment by ramirandaq** [comment]
Hi Greg, thanks for your interest in BitBIRCH! We are looking into this, but most likely the issue is related to how the fingerprints are generated. Most fingerprint generators will produce bitvectors, but BitBIRCH takes as input an array with np.int64 elements. @klopezperez is double-checking this, we'll get back to you shortly, but please let us know if you need anything else.

**Comment by greg-rezo** [comment]
Ah, that would make sense. If you share suggested example fingerprint usage, I can try it out and see if that helps.

**Comment by ramirandaq** [comment]
No problem, Pat Walters put together a very nice example on how to use BitBIRCH to cluster ChEMBL: https://gist.github.com/PatWalters/7c375353ff183be3eae925e0431398aa
Let me know if this works, or if you need anything else.

**Comment by greg-rezo** [comment]
Casting the fp vector to int64 seems to have fixed that issue. Thank you.
